### ISSUE TITLE
跑你的DEMO，加载更多时候会有错误

### ISSUE THREAD

**Issue by qaz349293703** [lovejjfg/PowerRecyclerView#2]
因为你是在监听scroll滚动状态时候，单纯判断了长度和isHasMore，而没有判断滚动状态。
if (adapter.getItemCount() > 1 && lastCompletelyVisibleItemPosition >= adapter.getItemCount() - 1 && adapter.isHasMore()) {
                adapter.isLoadingMore();
//                    if (null != listener) {
//                        listener.onLoadMore();
//                    }
            }
然后onLoadMore（）方法中调用notifyItemRangeChanged(getItemRealCount(), 1);方法就会报如下错误。

Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame.
                                                                                    java.lang.IllegalStateException: 
                                                                                        at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2403)
                                                                                        at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4626)
                                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:10462)
                                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:10453)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeChanged(RecyclerView.java:6167)
                                                                                        at com.lovejjfg.powerrecycle.PowerAdapter.isLoadingMore(PowerAdapter.java:219)
                                                                                        at com.lovejjfg.powerrecycle.LoadMoreScrollListener.onScrolled(LoadMoreScrollListener.java:51)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4305)
                                                                                        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4463)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:605)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by qaz349293703** [comment]
是在isLoadingMore()方法中调用notifyItemRangeChanged方法，打错了

**Comment by lovejjfg** [comment]
灰常抱歉，但是在我这边确实木有出现这个异常，你可以看看这个地址：http://stackoverflow.com/questions/39445330/cannot-call-notifyiteminserted-method-in-a-scroll-callback-recyclerview-v724-2
，有相关的解决方案。
